/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.cartas.GeneracionDeTablero;
import Backend.InformacionDificultad;
import Backend.cartas.Carta;
import Backend.motor.MotorJuego;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Phoenix
 */
public class VentanaJuego extends javax.swing.JFrame {

    private static InformacionDificultad infoDificultad;
    private static JFrame frameAnterior;

    /**
     * Creates new form Juego
     *
     * @param informacionDificultad
     */
    public VentanaJuego(InformacionDificultad informacionDificultad, JFrame frameAnterior) {

        this.infoDificultad = informacionDificultad;
        this.frameAnterior = frameAnterior;

        initComponents();
        crearTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTablero = new javax.swing.JPanel();
        btnNuevoJuego = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPunteoJugador1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPunteoJugador2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblJugadorEnTurno = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTablero.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        pnlTablero.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlTablero.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 535, 321));

        btnNuevoJuego.setText("NuevoJuego");
        btnNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Punteo Jugador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblPunteoJugador1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblPunteoJugador1.setForeground(new java.awt.Color(255, 255, 0));
        lblPunteoJugador1.setText(":");
        getContentPane().add(lblPunteoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Punteo Jugador ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        lblPunteoJugador2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblPunteoJugador2.setForeground(new java.awt.Color(255, 255, 0));
        lblPunteoJugador2.setText(":");
        getContentPane().add(lblPunteoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 104, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("P:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 22, -1));

        lblJugador1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblJugador1.setForeground(new java.awt.Color(255, 255, 0));
        lblJugador1.setText(":      ");
        getContentPane().add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("P:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 22, -1));

        lblJugador2.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        lblJugador2.setForeground(new java.awt.Color(255, 255, 0));
        lblJugador2.setText(":      ");
        getContentPane().add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 100, -1));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Turno del Jugador");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 227, 32);

        lblJugadorEnTurno.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        lblJugadorEnTurno.setForeground(new java.awt.Color(255, 0, 0));
        lblJugadorEnTurno.setText(":");
        jPanel1.add(lblJugadorEnTurno);
        lblJugadorEnTurno.setBounds(240, 10, 210, 32);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 460, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPartida.jpg"))); // NOI18N
        lblFondo.setText("jLabel6");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoJuegoActionPerformed
        this.dispose();
        frameAnterior.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoJuegoActionPerformed
    private void crearTodo() {
        GeneracionDeTablero tableroGenerado = new GeneracionDeTablero(pnlTablero, infoDificultad.getFilas(), infoDificultad.getColumnas());
        //aqui
        tableroGenerado.inicializarComponentes();
        MotorJuego motorJuego = new MotorJuego(this, tableroGenerado);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new VentanaJuego(infoDificultad, frameAnterior).setVisible(true);
            }
        });
    }

    public JLabel getLblJugador1() {
        return lblJugador1;
    }

    public JLabel getLblJugador2() {
        return lblJugador2;
    }

    public JLabel getLblJugadorEnTurno() {
        return lblJugadorEnTurno;
    }

    public JLabel getLblPunteoJugador1() {
        return lblPunteoJugador1;
    }

    public JLabel getLblPunteoJugador2() {
        return lblPunteoJugador2;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugadorEnTurno;
    private javax.swing.JLabel lblPunteoJugador1;
    private javax.swing.JLabel lblPunteoJugador2;
    private javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
